version: '3.8'

services:
  db:
    image: postgres:14.5-alpine
    env_file:
      - .env
    restart: always
    ports: 
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local