name: End-to-end Tests

on:
  deployment_status:
env:
  VITE_API_URL: ${{ vars.VITE_API_URL }}
  BASE_URL: ${{ vars.BASE_URL }}

jobs:
  run-e2es:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success' && github.event.deployment_status.environment == 'Preview'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: "Preview"
    steps:
      - name: Check github branch
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Check environment variables
        run: |
          echo "VITE_API_URL: $VITE_API_URL"
          echo "BASE_URL: $BASE_URL"
      - name: Run Playwright tests on Google Chrome
        run: npx playwright test --project=chromium
      - name: Run Playwright tests on Mozilla Firefox
        run: npx playwright test --project=firefox
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
